import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="border-b border-b-gray-300 px-3 h-14 flex items-center bg-gray-100">
          
        <Link
            className="py-2 rounded-md px-5 border border-gray-300 duration-300 hover:bg-blue-300 hover:border-blue-300 ml-auto mr-3"
            href={"/"}
          >
            Search
          </Link>
          <Link
            className="py-2 rounded-md px-5 border border-gray-300 duration-300 hover:bg-blue-300 hover:border-blue-300"
            href={"/dashboard"}
          >
            Dashboard
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
